### ISSUE TITLE
Ordered product qty over stock qty

### ISSUE THREAD

**Issue by 4t87ux8** [devansh-webkul/commerce#14]
Hello. There is such a mistake on the site. So, when ordering a product that has 2 in stock, it gives an error when choosing 3 as the number and adding it to the cart. This is clear. But when you select 2 pieces and add them to the cart, then click on the cart icon at the top, you can change the number, increase it to any number, and order from the side menu that opens. However, there are not so many products in stock

**Comment by VikasTiwari-Webkul** [comment]
@4t87ux8 Could you please elaborate more with some screenshots?

**Comment by 4t87ux8** [comment]
This problem fixed already. Thanks all
