### ISSUE TITLE
Graphql queries missmatch with backend

### ISSUE THREAD

**Issue by imorad87** [devansh-webkul/commerce#16]
### .env.local variables
```
COMMERCE_PROVIDER=@vercel/commerce-bagisto
BAGISTO_CURRENCY_CODE=USD
BAGISTO_STORE_ENDPOINT=http://localhost:8000/graphql
```

### Graphql query 
```
query getProductListing(
    $input: FilterProductListingInput
    $first: Int = 10
    $page: Int = 1
  ) {
    getProductListing(input: $input, first: $first, page: $page) {
      paginatorInfo {
        count
        currentPage
        lastPage
        total
      }
      data {
        ...productInfo
      }
    }
  }
  ```
 
Nextjs app is trying to fetch the above query but, fails because the `FilterProductListingInput` type doesn't have the same type name on the backend side. Below is the query declaration on the backend side
  
  ```
  extend type Query {
    products(input: FilterProductsInput @builder(method: "Webkul\\GraphQLAPI\\Queries\\Admin\\Catalog\\Products\\FilterProducts")): [Product!] @paginate(type: "PAGINATOR", defaultCount: 10, model: "Webkul\\GraphQLAPI\\Models\\Catalog\\Product")
}
  ```
  
  as you can see the backend query expects the input variable to be of type `FilterProductsInput` but the frontend is using `FilterProductListingInput`
  
  Using Bagisto version:  v2.0.0
  nextjs-commerce version: latest

![Screenshot 2024-04-12 at 9 06 22 PM](https://github.com/bagisto/nextjs-commerce/assets/10866647/80a59b05-5159-49a1-9546-8475e3c885ed)

**Comment by VikasTiwari-Webkul** [comment]
Hi @imorad87 

Thanks for raising concern.

Unfortunately, Bagisto Next Commerce is not compatible with Bagisto version: `v2.0.0`

The team is working on it soon we will deploy the Next Bagito Commerce 2.0

**Comment by imorad87** [comment]
@VikasTiwari-Webkul thank you for your reply

**Comment by VikasTiwari-Webkul** [comment]
[Bagisto Next Commerce - v2](https://github.com/bagisto/nextjs-commerce/tree/v2) is now released.

Which is compatible with Bagisto version: `v2.0.0`.

commit: https://github.com/bagisto/nextjs-commerce/commit/bed1c02d7e364b55385e53f5fbabb47cd49da9e5
