### ISSUE TITLE
Demo: Images point to offline `ngrok` instance

### ISSUE THREAD

**Issue by ndom91** [devansh-webkul/commerce#3]
Hi Team,

Was just clicking around the demo, and noticed that in the current deployment, all the images are attempting to be loaded from an `ngrok` instance, which is obviously no longer online / hostname potentially changed after restart.

See:

![image](https://user-images.githubusercontent.com/7415984/183431493-aa001a2c-85ae-471c-80ec-086a1ec8a704.png)

Just figured I'd bring this to your attention.

**Comment by devansh-webkul** [comment]
Yes for temporary purposes and testing we have done that. We will fix it.

**Comment by JakeOcean** [comment]
Any update here? It's not just the images, the cart and other AJAX calls fail too.

**Comment by devansh-webkul** [comment]
Issue fixed.
